/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rest.client.bug;

import java.net.URI;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import javax.ws.rs.core.Response;

import org.eclipse.microprofile.rest.client.RestClientBuilder;

public class App {
  public String getGreeting() {
    MyRestClient client = RestClientBuilder.newBuilder().register(JsonConfig.class)
        .baseUri(URI.create("http://localhost:3000")).connectTimeout(10000, TimeUnit.MILLISECONDS)
        .readTimeout(10000, TimeUnit.MILLISECONDS).build(MyRestClient.class);
    Response response = client.myCall(Map.of(new TypeFromSomeLib(), new TypeFromSomeLib()));
    return response.toString();
  }

  public static void main(String[] args) {
    new App().getGreeting();
  }
}
